### ISSUE TITLE
Display long description in list view.

### ISSUE THREAD

**Issue by kppullin** [mruangutai/project-goldeneye#2]
It seems like it'd be better to show the long description of the code in the list view, instead of or in conjunction with the short description.  The long descriptions have more details and are much easier to read.
#### Example

> 006.0
> Ac Amebiasis W/O Abscess
> Acute amebic dysentery without mention of abscess

or

> 006.0
> Ac Amebiasis W/O Abscess (Acute amebic dysentery without mention of abscess)`

etc...

vs this:

> 006.0
> Ac Amebiasis W/O Abscess

**Comment by joesomoza** [comment]
I think this is a great idea! Let me talk to Lee.

**Comment by kppullin** [comment]
Ok rad maybe you can show me how it works Wednesday evening at the hack
thingy

Sent from my phone

**Comment by joesomoza** [comment]
Done.
